spring:
  application:
    name: weather-api
  redis:
    host: 192.168.25.103
    port: 6379
server:
  port: 8020

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/