server:
  port: 8050
spring:
  application:
    name: weather-gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    cityRoute:
      service-id: weather-city-collection
      path: /city/**
    weatherRoute:
      service-id: weather-api
      path: /weather/**