server:
  port: 8010
spring:
  application:
    name: weather-collection
  redis:
    host: 192.168.25.103
    port: 6379
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/